### PR TITLE
Add results of total time taken for all requests + structure changes

### PR DESCRIPTION
**Pull request by agamm**
Add a way to see total time.

### CODE REVIEW

**Review by mildsunrise — COMMENTED** [review]
Why would you want to see total time *sum* for all the requests?
How would that be useful? :thinking:

**Comment by agamm** [comment]
@jmendeth, for example, I'm doing performance testing of N requests. So getting the total time it took is really helpful. That is essentially what I'm trying to test, so all of the other outputs are nice but not my main test indicator.
Ie, Test 100 requests to mysite.com(25s) and 100 to mynewsite.com (20s), and see if there are any changes in the total time it took those 100 requests. So in this example, I can see that mynewsite is faster by 5s, I know it is not super precise but it is a good enough indicator for me now.

**Comment by mildsunrise** [comment]
Hmm, I understand, but wouldn't it be better to work with *per request* total time?

I.e. 25s / 100 requests = 250ms average time per request.
20s / 100 requests = 200ms average time per request.

Comparing 250ms vs 200ms makes more sense to me, and curl-benchmark already provides that information, you just have to add the **avg** values together! In this example:

example shot

6.4 + 43.7 + 240.8 + 174.0 + 144.3 = 609ms average time per request (which is 6.09s total time)

**Comment by agamm** [comment]
> Hmm, I understand, but wouldn't it be better to work with _per request_ total time?
> 
> I.e. 25s / 100 requests = 250ms average time per request.
> 20s / 100 requests = 200ms average time per request.
> 
> Comparing 250ms vs 200ms makes more sense to me, and curl-benchmark already provides that information, you just have to add the **avg** values together! In this example:
> 
> example shot
> 
> 6.4 + 43.7 + 240.8 + 174.0 + 144.3 = 609ms average time per request (which is 6.09s total time)

You are totally right, but this branch feature isn't in conflict. We just add additional information that helps instead of having to compute it manually. It's only an addition, not a replacement.

**Comment by agamm** [comment]
I guess you don't want to add this.

**Pull request closed without merging**
